(function(g){var window=this;'use strict';var K3=function(a){a.ra("cardstatechange",a.Nk()&&a.hp()?1:0)},L3=function(a,b){var c=g.ab(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},wmb=function(a){var b=g.us(a);
a=g.xs(a);return new g.is(b.x,b.y,a.width,a.height)},xmb=function(a,b,c){var d=void 0===d?{}:d;
var e;return e=g.uC(a,b,function(){g.vC(e);c.apply(a,arguments)},d)},O3=function(a){a=g.fb(a);
delete M3[a];g.md(M3)&&N3&&N3.stop()},zmb=function(){N3||(N3=new g.Ru(function(){ymb()},20));
var a=N3;a.isActive()||a.start()},ymb=function(){var a=g.kb();
g.bd(M3,function(b){Amb(b,a)});
g.md(M3)||zmb()},P3=function(a,b,c,d){g.dv.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},Amb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;Bmb(a,a.progress);1==a.progress?(a.j=0,O3(a),a.onFinish(),a.vr()):a.isPlaying()&&a.IL()},Bmb=function(a,b){"function"===typeof a.G&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},Cmb=function(a,b){g.Ab.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},Q3=function(a,b,c,d,e){P3.call(this,b,c,d,e);
this.element=a},Dmb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
Q3.call(this,a,b,c,d,e)},Emb=function(a){return Math.pow(a,3)},Fmb=function(a){return 3*a*a-2*a*a*a},Gmb=function(a){g.I.call(this);
this.B=a||window;this.j=[]},R3=function(a){return a.baseUrl||null},S3=function(a,b){return g.pt(g.Fr(a,b),function(c){return!!c})},Hmb=function(a,b,c){function d(ta){var la=ta.hovercardButton;
if(!la)return null;la=la.subscribeButtonRenderer;if(!la)return null;var va=f(la.unsubscribedButtonText),ea=f(la.subscribedButtonText);if(la.subscribed){var Y=f(la.subscriberCountWithUnsubscribeText);var Na=f(la.subscriberCountText)}else Y=f(la.subscriberCountText),Na=f(la.subscriberCountWithSubscribeText);var y=null;if(ta.signinEndpoint){y=L3(ta,"signinEndpoint","webNavigationEndpointData","url");if(!y){var ca,Ja;y=null==(Ja=g.U(null==(ca=la.signInEndpoint)?void 0:ca.commandMetadata,g.F2))?void 0:
Ja.url}if(!y)return null}return va&&(ea||y)?{subscribed:la.subscribed,subscribeText:va,subscribeCount:Y,unsubscribeText:ea,unsubscribeCount:Na,enabled:la.enabled,signinUrl:y,classic:ta.useClassicSubscribeButton}:null}
function e(ta){if(ta){var la=[],va=ta.videoId;va&&la.push("v="+va);(va=ta.playlistId)&&la.push("list="+va);(ta=ta.startTimeSeconds)&&la.push("t="+ta);return"/watch?"+la.join("&")}}
function f(ta){if(!ta)return null;var la=ta.simpleText;return la?la:ta.runs?g.Fr(ta.runs,function(va){return va.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,v=null,x=!1,A=null,E=null,F=null,G=null,L=null,Q=null;if("VIDEO"===h)g.U(l,g.eG)?m=g.U(l,g.eG).url:(Q=g.U(l,g.dT),m=e(Q)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.U(l,g.eG)?m=g.U(l,g.eG).url:(Q=g.U(l,g.dT),m=e(Q)),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===
h){if(x=L3(l,"browseEndpoint","browseId"))v=x,m="/channel/"+v;n=!1;q="new";(x=!!b.isSubscribe)?A=d(b):E=f(b.subscribersText)}else"WEBSITE"===h?((F=L3(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=L3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=L3(b,"title","accessibility","accessibilityData","label");var R=b.endpoint?b.endpoint.clickTrackingParams:null,
aa="";if(b.metadata){var na=f(b.metadata);na&&(aa=na)}return{id:"element-"+c,type:h,title:f(b.title),metadata:aa,callToAction:f(b.callToAction),tW:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,lE:p,playlistLength:t,channelId:v,subscribeButton:A,subscribersText:E,isSubscribe:x,targetUrl:m||null,F8:n,sessionData:R?{itct:R}:null,dda:q,LC:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:S3(b.impressionUrls||[],R3),r8:S3(b.hovercardShowUrls||[],R3),clickUrls:S3(l.loggingUrls||[],R3),visualElement:g.jF(b.trackingParams),productPrice:G,additionalFeesText:L,watchEndpoint:Q||null}},Imb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:S3(a.impressionUrls||[],R3),elements:S3(a.elements||[],function(d,e){return Hmb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.jF(a.trackingParams));return c},Jmb=function(a){g.NV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.VR(a)||g.YR(a);this.events=new g.DK(this);g.N(this,this.events);this.events.T(this.player,g.QJ("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.RJ("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Yb);this.events.T(window,"focus",this.oba);this.load();var b=g.If("STYLE");(g.xf("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.Rf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Kmb=function(a){return a.player.getVideoData().Pf?"current":a.Z?"new":"current"},T3=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},Lmb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=Imb(f,Kmb(a))));U3(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.Rx;d&&(c.postParams={ad_tracking:d});if(b=g.QTa(b))if(b=g.ye(b),b=g.he(b))a.C=g.MB(b,c)},U3=function(a,b,c){c=void 0===c?!0:c;
a.player.Ff("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.u(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};0<a.N.length&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&Mmb(a);c=[];d=new g.PJ(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.V({I:"div",S:"ytp-ce-shadow"}),g.kU(a.player,a.B.element,4),a.D=new g.xG(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Nmb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.kU(a.player,f.element,4);var h=new g.PJ(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Omb(a,f,e)}else g.pF(new g.LC("buildEndscreenElement null",
e))}a.player.Bf(c);a.Yb()}},Mmb=function(a){var b=g.kF(),c=g.lF();
c&&b&&a.endscreen.visualElement&&g.qB(g.yF)(void 0,c,b,a.endscreen.visualElement)},Nmb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",La:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.LC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:V3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:W3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",La:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.pv(b.title||"")},ya:b.title},{I:"div",S:b.lE?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
ya:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":a={I:"div",La:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.LC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:V3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:W3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",La:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.pv(b.title||"")},ya:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",ya:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={I:"div",La:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.LC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",La:["ytp-ce-channel-title","ytp-ce-link"],X:{href:W3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.pv(b.title||"")},ya:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",ya:b.subscribersText}:"",b.metadata?{I:"div",La:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],ya:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:V3(b)}]};c=new g.V(c);var d=g.yf(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Zu(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.vW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",La:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.LC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",X:{dir:g.pv(b.title||"")},ya:b.title},{I:"div",S:"ytp-ce-website-metadata",ya:b.metadata},{I:"a",La:["ytp-ce-website-goto","ytp-ce-link"],X:{href:W3(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:V3(b)},{I:"div",S:"ytp-ce-expanding-icon",X:Pmb(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",ya:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",ya:b.additionalFeesText})),a={I:"div",La:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.LC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",X:{dir:g.pv(b.title||"")},ya:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",ya:b.metadata},{I:"a",La:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:W3(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:V3(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
ya:b.callToAction||void 0}]}]},c=new g.V(a)}b.isPlaceholder&&g.Zu(c.element,"ytp-ce-placeholder");return c},V3=function(a){if(a.tW)var b=a.tW.thumbnails;
return Pmb(b?b[b.length-1].url:null)},Pmb=function(a){return a?{style:"background-image: url("+a+")"}:{}},Omb=function(a,b,c){function d(m){m&&(b.Ta("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;0<a.K?(g.Zu(b.element,"ytp-ce-force-expand"),X3(a,c.id,!0)):(g.av(b.element,"ytp-ce-force-expand"),g.av(b.element,"ytp-ce-element-hover"),X3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ta("mouseenter",function(){Qmb(a,b,c)});
b.Ta("mouseleave",function(){Rmb(a,b,c)});
a.player.U().B||b.Ta("click",function(){g.Zu(b.element,"ytp-ce-element-hover")});
b.Ta("click",function(m){Smb(a,c,m)});
b.Ta("keypress",function(m){Smb(a,c,m)});
b.Ta("focus",function(){Qmb(a,b,c)});
b.Ta("blur",function(){Rmb(a,b,c)});
b.Ta("touchstart",function(){Qmb(a,b,c)});
var l=g.Af("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.av(b.element,"ytp-ce-element-hover");g.av(b.element,"ytp-ce-force-expand")});
b.Ta("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.Af("ytp-sb-subscribe",b.element));d(g.Af("ytp-sb-unsubscribe",b.element));b.Ta("focus",f);b.Ta("blur",h)},Smb=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Yu(d,"ytp-ce-element");){g.Yu(d,"subscribe-label")&&Tmb(a,b);
if(g.Yu(d,"ytp-ce-channel-subscribe"))return;d=g.Sf(d)}if(!d||g.Yu(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Rmb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.dda)Tmb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.ye(W3(a,b.targetUrl)),g.ZG(g.he(c),void 0,b.sessionData);else{var e=g.gS(a.player.U())||a.player.getVideoData().Pf,f=function(){var h=W3(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.vB(h);e&&n&&(n.v||
n.list)?a.player.No(n.v,l,n.list,!1,void 0,m||void 0):g.Nxa(h,l)};
Tmb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},W3=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.nS(a)+b}else return"";return b},Qmb=function(a,b,c){g.Yu(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.Zu(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.Ru(function(){g.Zu(b.element,"ytp-ce-element-hover")},200)).start():g.Zu(b.element,"ytp-ce-element-hover"),Y3(a,c.r8),X3(a,c.id,!0))},Rmb=function(a,b,c){g.av(b.element,"ytp-ce-element-hover");
g.av(b.element,"ytp-ce-force-expand");X3(a,c.id,!1)},X3=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.u(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.cv(a.j[e].element,"ytp-ce-element-shadow-show",c)},Y3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||T3(a))c&&c();else{b=Umb(a,b);var e=0,f=!1,h=new g.Ru(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.eE(b[a],d)}},Tmb=function(a,b,c){Y3(a,b.clickUrls,c);
(a=g.lF())&&b.F8&&g.FF(a,b.visualElement)},Umb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Vmb(b[d],c));return a},Vmb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Wmb=function(a){return"string"===typeof a?a:""},Z3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Xmb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},$3=function(a){return a.value?a.value:null},a4=function(a){if(!a)return null;
var b=g.ye(Wmb(a.value));b=g.he(b);if(!b)return null;var c=Z3(a.target,Ymb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Xmb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Zmb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},bnb=function(a){if(!a)return null;
var b=Z3(a.type,$mb),c=Z3(a.trigger,anb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=a4(a?a:null);return b?new Zmb(b,c,a):null},cnb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},dnb=function(a,b){return g.Db(a.action,b)},enb=function(a,b){this.context=a;
this.j=b},fnb=function(a){return a.customMessage?b4("div","iv-card-message",a.customMessage):""},c4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",X:{style:a},V:c}},gnb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.u(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(b4("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},b4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.pv(c);return{I:a,X:b,ya:c}},hnb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.VC&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.VC+");");c.dir=g.pv(a.customMessage);var d=[{I:"span",ya:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",La:b,X:c,V:d}},d4=function(a,b,c,d){if(d){b=g.u(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.nj.click,5)}},inb=function(a,b){this.merchant=a;
this.price=b},jnb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},knb=function(a,b){return b?b:jnb(a)?"current":"new"},e4=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.tb=!1;this.Xa=new Map;this.eb=new Map;this.context.J.addEventListener(g.QJ("annotations_module"),function(d){(d=c.Xa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.RJ("annotations_module"),function(d){(d=c.eb.get(d))&&d.apply(c)})},f4=function(a,b,c,d,e,f,h){a.context.j.Ta(b,"click",function(l){a.JL(c,d,e,f||[],h||0,l)});
a.context.j.Ta(b,"touchstart",function(){a.tb=!1});
a.context.j.Ta(b,"touchmove",function(){a.tb=!0})},lnb=function(a){var b;
return(null==(b=g.U(a,g.eG))?0:b.url)?g.U(a,g.eG).url:(a=g.U(a,g.dT))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},g4=function(a,b,c){return{YX:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
B0:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
YK:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},mnb=function(a,b,c){e4.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Db=this.Na=this.Pb=this.C=this.isInitialized=!1;this.cards=[];this.ub=this.Z=this.Ma=this.G=this.Wa=this.j=null;this.ma=[];this.va=this.N=this.Mf=this.Ea=null;this.K=0;this.Ia=new g.Ru(function(){},c.W.Jl?4E3:3E3);
g.N(this,this.Ia);this.ib=new g.Ru(function(){});
g.N(this,this.ib);this.Ca=new enb(c,function(e,f,h,l,m,n){f4(d,e,f,h,l,m,n)});
this.Y=new g.V({I:"div",S:"iv-drawer",X:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",X:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",La:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.N(this,this.Y);this.D=this.Y.element;this.Za=new g.xG(this.Y,330);g.N(this,this.Za);this.Mb=g.Af("iv-drawer-header-text",this.D);this.B=g.Af("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Pb&&h4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Pb=d.C)&&i4(d)});
this.Ra=new g.DK(this);g.N(this,this.Ra);this.J.addEventListener("videodatachange",this.nt.bind(this))},nnb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){h4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){i4(a)});
var c=b.headerText;g.Vf(a.Mb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ea=g.jF(b.trackingParams);a.N=g.jF(b.closeTrackingParams);a.Mf=g.jF(b.iconTrackingParams)},onb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.jb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.TF(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,nj:{},kp:null,Qj:e.trackingParams?g.jF(e.trackingParams):null,Mf:f&&f.trackingParams?g.jF(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
VC:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};j4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.TF(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:k4(a,c,b,f),sponsored:!1,nj:g4(f,e,f.command),kp:f.trackingParams?g.jF(f.trackingParams):null,Qj:e.trackingParams?g.jF(e.trackingParams):null,Mf:l&&l.trackingParams?g.jF(l.trackingParams):null,imageUrl:l4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.TF(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,VC:null,title:f.title?g.TF(f.title):"",customMessage:f.callToAction?g.TF(f.callToAction):"",url:g.U(f.command,g.eG).url?a4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.U(f.command,g.eG).url}):null,onClickCommand:null};j4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.TF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:k4(a,c,b,e),sponsored:!1,nj:g4(e,f,e.endpoint),kp:e.trackingParams?g.jF(e.trackingParams):null,Qj:f.trackingParams?g.jF(f.trackingParams):null,Mf:l&&l.trackingParams?g.jF(l.trackingParams):null,channelId:g.U(e.endpoint,g.sT).browseId,customMessage:e.customText?g.TF(e.customText):null,profileImageUrl:l4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.TF(e.channelName):"",metaInfo:[e.subscriberCountText?g.TF(e.subscriberCountText):""],url:a4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.U(e.endpoint,g.sT).canonicalBaseUrl?g.U(e.endpoint,g.sT).canonicalBaseUrl:"/channel/"+g.U(e.endpoint,g.sT).browseId}),onClickCommand:null};j4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.TF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:k4(a,c,b,e),sponsored:!1,nj:g4(e,f,e.action),kp:e.trackingParams?g.jF(e.trackingParams):null,Qj:f.trackingParams?g.jF(f.trackingParams):null,Mf:l&&l.trackingParams?g.jF(l.trackingParams):null,pG:l4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.TF(e.customMessage):null,playlistVideoCount:g.TF(e.playlistVideoCount),title:e.playlistTitle?g.TF(e.playlistTitle):"",metaInfo:[e.channelName?g.TF(e.channelName):
"",e.videoCountText?g.TF(e.videoCountText):""],url:a4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:lnb(e.action)}),onClickCommand:null};j4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.TF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:k4(a,c,b,e),sponsored:!1,nj:g4(e,f,e.action),kp:e.trackingParams?g.jF(e.trackingParams):null,Qj:f.trackingParams?g.jF(f.trackingParams):null,Mf:l&&l.trackingParams?g.jF(l.trackingParams):null,pG:l4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.TF(e.lengthString):null,customMessage:e.customMessage?g.TF(e.customMessage):null,title:e.videoTitle?g.TF(e.videoTitle):"",metaInfo:[e.channelName?g.TF(e.channelName):
"",e.viewCountText?g.TF(e.viewCountText):""],isLiveNow:!!e.badge,url:a4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:lnb(e.action)}),onClickCommand:null};j4(a,b)}}}}}a.K++},l4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},k4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},qnb=function(a,b){if(b=pnb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.If.id),g.Rf(b.cN),g.Ib(a.cards,b),a.kH(),m4(a)},h4=function(a,b,c){if(!a.C){a.Za.show();
a.Wa=new g.Ru(function(){g.Zu(a.context.J.getRootNode(),g.hZ.IV_DRAWER_OPEN)},0);
a.Wa.start();a.Ra.T(a.B,"mousewheel",function(h){a.Ia.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.lF();d&&a.Ea&&a.N&&g.DF(d,[a.Ea,a.N]);b={TRIGGER_TYPE:b};for(var e=g.u(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.PY||(f.PY=!0,rnb(a.context.logger,f.If.nj.YX,b)),d&&g.DF(d,[f.If.kp]);K3(a.J);c&&(a.G=new g.Ru(function(){a.Ma=a.Z;a.ub.focus()},330),a.G.start())}},i4=function(a){a.C&&(a.Za.hide(),g.AC(a.Ra),g.av(a.context.J.getRootNode(),g.hZ.IV_DRAWER_OPEN),a.C=!1,K3(a.J),a.G&&a.G.stop(),a.G=new g.Ru(function(){a.Ma&&(a.Ma.focus(),a.Ma=null)},330),a.G.start())},tnb=function(a){g.$u(a.Kb(),
[g.hZ.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.kU(a.J,a.D,5);snb(a);a.Z=g.Af("ytp-cards-button",a.J.getRootNode());a.ub=g.Af("iv-drawer-close-button",a.D);a.isInitialized=!0},snb=function(a){var b=g.Af("iv-drawer-close-button",a.D);
a.context.j.Ta(b,"click",a.Z5,a);a.context.j.Ta(a.B,"touchend",function(){a.Ia.start()});
a.context.j.Ta(a.B,"scroll",a.x6,a);a.context.B.subscribe("onHideControls",function(){a.Na=!0});
a.context.B.subscribe("onShowControls",function(){a.Na=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.Na=g.Yu(a.J.getRootNode(),"ytp-autohide")});
a.ma.push(g.sE("iv-button-shown",a.X8,a));a.ma.push(g.sE("iv-button-hidden",a.W8,a));unb(a)},unb=function(a){a.ma.push(g.sE("iv-teaser-shown",a.D2,a));
a.ma.push(g.sE("iv-teaser-hidden",a.Y8,a));a.ma.push(g.sE("iv-teaser-clicked",a.C2,a));a.Db=!0},vnb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.U(b.onClickCommand,g.Uib))?void 0:c.targetId)?(a.va=b,!0):!1},wnb=function(a,b){a.va=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.oSa(c);if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.U(h[0],g.R0a))?void 0:d.timeRangeStartMillis)||0,a.va=null,!0}return!1},j4=function(a,b){if(!vnb(a,b)||wnb(a,b)){var c=xnb(a,b);
if(c){var d={If:b,cN:c.element,PY:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Db||unb(a),qnb(a,b.id),c=a.findLastIndex(d),g.Rb(a.cards,c,0,d));else{a.isInitialized||tnb(a);qnb(a,b.id);var e=a.findLastIndex(d);g.Rb(a.cards,e,0,d);c.Ja(a.B,e);a.kH()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,m4(a),ynb(a,d),h4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&znb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){znb(a,d)}),m4(a))}}},xnb=function(a,b){switch(b.type){case "simple":a=a.Ca;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",ya:b.displayDomain}:void 0;var d=hnb(b);c={I:"div",La:["iv-card"],V:[{I:"a",S:"iv-click-target",X:{href:b.url?$3(b.url)||"":""},V:[c4(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[b4("h2",void 0,b.title),d]}]}]};c=new g.V(c);d4(a,g.zf("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ca;c={I:"div",La:["iv-card","iv-card-channel"],V:[{I:"a",La:["iv-click-target"],X:{href:$3(b.url)||"","data-ytid":b.channelId},V:[c4(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[fnb(b),{I:"h2",S:"iv-card-primary-link",ya:b.title},gnb(b)]}]}]};c=new g.V(c);d4(a,g.zf("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ca;c={I:"div",La:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",X:{href:$3(b.url)||""},V:[c4(b.pG,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",ya:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[fnb(b),b4("h2","iv-card-primary-link",b.title),gnb(b)]}]}]};
c=new g.V(c);d4(a,g.zf("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ca;var e=0!=b.offers.length;c=["iv-card"];d="";var f=hnb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",ya:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",ya:f.merchant}),f={I:"div",V:e});e=b.url?$3(b.url)||"":"";c={I:"div",La:c,X:{tabindex:"0"},V:[{I:"a",La:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",ya:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",X:{href:e},V:[b4("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.If("span");g.Vf(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Vd(d,"adInfo");d4(a,g.zf("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ca;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",ya:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",La:["yt-badge","yt-badge-live"],ya:"LIVE NOW"}:null;e={I:"div",La:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",X:{href:(null==(c=b.url)?void 0:$3(c))||""},V:[c4(b.pG,d),{I:"div",S:"iv-card-content",V:[fnb(b),b4("h2","iv-card-primary-link",b.title),gnb(b),f]}]}]};c=new g.V(e);d4(a,g.zf("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},Anb=function(a){if(a.j)return"productListing"===a.j.If.type;
if(a.J.L("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.Gr(a.cards,function(c){return"productListing"===c.If.type})}return g.Gr(a.cards,function(c){return"productListing"===c.If.type})},m4=function(a){g.cv(a.J.getRootNode(),"ytp-cards-shopping-active",Anb(a))},znb=function(a,b){if(!g.Yu(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.lF(),d=a.j?a.j.If.Mf:a.Mf;
c&&d&&g.EF(c,[d]);a.j=b;m4(a)}(c=a.isInitialized&&"none"==a.Kb().style.display)||(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=!(1===c||3===c||d));c||b.If.teaserDurationMs&&a.J.qB(!0,{teaserText:b.If.teaserText,durationMs:b.If.teaserDurationMs,onClickCommand:b.If.onClickCommand});a.ib.isActive()||((!a.C||!a.Ia.isActive()&&a.Na)&&ynb(a,b),a.ib.start(910+b.If.teaserDurationMs))}},ynb=function(a,b){a.Y.Jb?(b=new P3([0,
a.B.scrollTop],[0,b.cN.offsetTop],600,Fmb),a.context.C.Ta(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.Ta(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.PF(a.Y,!0),a.B.scrollTop=b.cN.offsetTop,g.PF(a.Y,!1))},n4=function(a){return a.j&&a.j.If?a.j.If:a.cards[0]&&a.cards[0].If?a.cards[0].If:null},pnb=function(a,b){return g.Db(a.cards,function(c){return c.If.id===b})},o4=function(a,b,c){e4.call(this,a,b);
this.annotation=c;this.isActive=!1},Bnb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},p4=function(a,b,c){o4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},Cnb=function(a,b){var c=void 0===c?0:c;
var d=wmb(b).width;g.rs(b,d);c=new Dmb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Emb);g.N(a,c);a.context.C.Ta(c,"begin",function(){g.ys(b,!0)});
c.play()},Fnb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
La:["iv-branding-context-name"],ya:b.channel_name}),d=a.createElement({I:"div",La:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.vW(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ja(d));var f=a.createElement({I:"div",La:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",La:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.ys(h,!1);var l=a.createElement({I:"div",La:["branding-context-container-outer"]});l.appendChild(h);g.ls(l,"right",b.image_width+"px");g.Of(a.Kb(),l);a.C=new g.Ru(function(){Dnb(a,h,l)},500);
g.N(a,a.C);a.context.j.Ta(a.Kb(),"mouseover",function(){Enb(a,h,l,f,b.image_height)});
a.context.j.Ta(a.Kb(),"mouseout",function(){a.C.start()})}},Enb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.xs(b);a.j||(b.style.width=g.qs(f.width,!0),c.style.width=g.qs(f.width,!0));g.ls(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.ls(d,"right","1px");a.D=!0;g.ys(b,!0);a.G=new g.Ru(function(){g.Zu(this.Kb(),"iv-branding-active")},0,a);
a.G.start()}},Dnb=function(a,b,c){g.av(a.Kb(),"iv-branding-active");
a.K=new g.Ru(function(){g.ys(b,!1);a.j||(c.style.width=g.qs(0,!0))},250);
a.K.start();a.D=!1},Gnb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.W=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},Hnb=function(a,b,c){o4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",La:["iv-promo-contents"]});this.G=new g.Ru(function(){d.j.setAttribute("aria-hidden","true");g.ys(d.C,!1);g.ys(d.B,!0)},700,this);
g.N(this,this.G)},Knb=function(a,b,c){c.stopPropagation();
Inb(a);Jnb(a,b);a.j.focus()},Lnb=function(a){a.isCollapsed||a.Z||a.D||(g.Zu(a.Kb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},Inb=function(a){a.G.stop();
a.isCollapsed&&(g.bv(a.Kb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.ys(a.B,!1),g.ys(a.C,!0))},Jnb=function(a,b){a.D||(a.D=g.yg(function(){Mnb(this);
Lnb(this)},b,a))},Mnb=function(a){a.D&&(g.Ta.clearTimeout(a.D),a.D=null)},Nnb=function(a){this.J=a},rnb=function(a,b,c){b&&(c?q4(a,b.map(function(d){return g.Gu(d,c)})):q4(a,b))},q4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.u(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.eE(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},Onb=function(a){g.NV.call(this,a);
var b=this;this.ma=this.Z=!1;this.loadNumber=0;this.N={};this.logger=new Nnb(this.player);this.D=new g.DK(this);this.G=this.K=null;this.events=new g.DK(this);this.dh=this.Y=this.j=null;this.va=[];g.N(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.ra("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.ra("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.ra("onShowControls")});
this.D.T(this.player,"resize",function(d){b.ra("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.ra("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.E2,this);this.subscribe("resize",this.OJ,this);this.player.U().Na.subscribe("vast_info_card_add",this.SZ,this);g.N(this,this.events);this.Ca=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.V({I:"div",La:["ytp-player-content","ytp-iv-player-content"]});g.N(this,this.B);g.kU(this.player,this.B.element,4);this.B.hide();this.C=new g.V({I:"div",La:["ytp-iv-video-content"]});g.N(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.Ca);this.C.element.appendChild(a);this.du()&&this.load();var c=this.createElement({I:"style"});(g.xf("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.Rf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Pnb=function(a){a=a.createElement({I:"div",
La:["annotation","annotation-type-custom"]});g.ys(a,!1);return a},Qnb=function(a,b){b=!b.isCued()&&!g.EG(b,1024);
g.PF(a.B,b);g.PF(a.C,b)},Rnb=function(a,b,c){a.Z=!0;
a.G=g.MB(b,c)},Snb=function(a,b){for(var c={},d=g.u(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.bb(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Snb(a,e))}return c},Wnb=function(a){var b=a.player.getVideoData();
if(b.Wa){var c=a.player.U().Na.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.FB(h)&&h.responseXML?h.responseXML:null)&&Tnb(a,h)}};
g.TC()&&(d.onFinish=Unb(a,d.onFinish));d.postParams={ic_only:"1"};Vnb(d,c);a.Z=!0;g.MB(b.Wa,d)}}},Vnb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.pH&&(a.postParams.ic_coll=b.pH);b.dN&&(a.postParams.ic_xml=b.dN);b.dL&&(a.postParams.ic_track=b.dL)},Xnb=function(a){var b=new g.V({I:"div"});
g.ys(b.element,!1);var c=new mnb(a.player,b.element,r4(a));g.N(c,b);b.Ja(a.B.element);c.YF();return c},Znb=function(a,b){var c,d;
if(b=null==(c=b.getWatchNextResponse())?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.ma=!0,Ynb(a,b),b.headerText&&a.dh&&(c=g.TF(b.headerText),a.dh.setAttribute("title",c))},r4=function(a){if(!a.Y){var b=new Gmb(a);
g.N(a,b);var c=new g.Fp(a);g.N(a,c);a.Y=new Gnb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.Aj)}return a.Y},Tnb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.lF();if(e){var f=g.kF();f&&g.qB(g.lwa)(void 0,e,f,[g.jF(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Snb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=Z3(f.type,$nb),p=Z3(f.style,aob),q=Wmb(f.data),r=0!==q.length?JSON.parse(q):{};var t=f.action;f=bnb;if(null==t)var v=null;else if(g.ab(t)){l=[];for(var x=g.u(t),A=x.next();!A.done;A=x.next()){var E=f(A.value);
E&&l.push(E)}v=l}else{var F=f(t);v=F?[F]:[]}e=m&&n?new cnb(m,n,p,v,r):null}else e=null}catch(na){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var G=Pnb(f),L=null;switch(l.type){case "branding":if(f.player.U().Ge)break;f.B.element.appendChild(G);L=new p4(G,r4(f),l);break;case "promotion":g.kU(f.player,G,4),L=new Hnb(G,r4(f),l)}L&&L.YF();if(f=L)g.N(a,f),a.N[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=Xnb(a),g.N(a,a.j));if("card"===e.type){G=a.j;var Q=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(Q)switch(f=e.tracking||{},f={YX:f.impression,click:f.click,close:f.close,B0:f.teaser_impression,YK:f.teaser_click},l=e.tracking_params||{},L=null,Q){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,nj:f,kp:l.card?g.jF(l.card):null,Qj:l.teaser?g.jF(l.teaser):null,Mf:l.icon?g.jF(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:a4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};j4(G,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,nj:f,
kp:l.card?g.jF(l.card):null,Qj:l.teaser?g.jF(l.teaser):null,Mf:l.icon?g.jF(l.icon):null,pG:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:a4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};j4(G,c);break;case "productListing":e.signin_url&&(L=a4({target:"current",value:e.signin_url}));Q=[];for(var R=e.offers||[],aa=0;aa<R.length;aa++)Q.push(new inb(g.gf(R[aa].merchant),
g.gf(R[aa].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,nj:f,kp:l.card?g.jF(l.card):null,Qj:l.teaser?g.jF(l.teaser):null,Mf:l.icon?g.jF(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,VC:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:a4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),Vob:L,Uob:e.signin_title?e.signin_title:void 0,Tob:e.signin_message?e.signin_message:void 0,offers:Q,onClickCommand:null};j4(G,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,nj:f,kp:l.card?g.jF(l.card):
null,Qj:l.teaser?g.jF(l.teaser):null,Mf:l.icon?g.jF(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,VC:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:a4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};j4(G,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,nj:f,kp:l.card?g.jF(l.card):null,Qj:l.teaser?g.jF(l.teaser):null,Mf:l.icon?g.jF(l.icon):null,pG:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:a4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},j4(G,c)}}else nnb(a.j,e);c=!0}}c&&
(K3(a.player),a.OJ())},Ynb=function(a,b){var c=!1;
a.j||(a.j=Xnb(a),g.N(a,a.j));for(var d=g.u(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(onb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.zT(f)||(c=a.j,d=b.headerText?g.TF(b.headerText):"",g.Vf(c.Mb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ea=b.trackingParams?g.jF(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.jF(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Mf=b.icon.infoCardIconRenderer.trackingParams?g.jF(b.icon.infoCardIconRenderer.trackingParams):null,a.OJ());K3(a.player)}},bob=function(a,b,c,d,e){if(!a.player.U().Ge){var f=[];
b.navigationEndpoint&&g.U(b.navigationEndpoint,g.sT)&&g.U(b.navigationEndpoint,g.sT).browseId&&f.push(new Zmb("openUrl","click",new Xmb("/channel/"+g.U(b.navigationEndpoint,g.sT).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.U(b.subscribeButton,
g.tT)){d.channel_id=g.U(b.subscribeButton,g.tT).channelId;var l;b=g.U(b.subscribeButton,g.tT);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.TF(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.TF(b.subscriberCountText))):(b.subscriberCountText&&(e=g.TF(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.TF(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.U(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.F2))?void 0:m.url)||"";l={subscribeText:g.TF(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.TF(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new cnb(c,"branding","branding",f,d);l=Pnb(a);a.B.element.appendChild(l);f=new p4(l,r4(a),f);f.YF();g.N(f,f);a.N[c]=f}},Unb=function(a,b){return function(){var c=g.Ia.apply(0,arguments);
a.isDisposed()||a.va.push(g.Ju.Yi(function(){b.apply(null,g.pa(c))}))}},cob=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.dU.prototype.qB=g.fa(29,function(a,b){var c=g.dW(this.Bb());c&&c.qB(a,b)});
var M3={},N3=null;g.ob(P3,g.dv);g.k=P3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;O3(this);this.startTime=a=g.kb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.FJ();this.Zl("play");this.isPaused()&&this.Zl("resume");this.j=1;var b=g.fb(this);b in M3||(M3[b]=this);zmb();Amb(this,a);return!0};
g.k.stop=function(a){O3(this);this.j=0;a&&(this.progress=1);Bmb(this,this.progress);this.Zl("stop");this.vr()};
g.k.pause=function(){this.isPlaying()&&(O3(this),this.j=-1,this.Zl("pause"))};
g.k.xa=function(){0==this.j||this.stop(!1);this.Zl("destroy");P3.Vf.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.IL=function(){this.Zl("animate")};
g.k.Zl=function(a){this.dispatchEvent(new Cmb(a,this))};
g.ob(Cmb,g.Ab);g.ob(Q3,P3);Q3.prototype.C=function(){};
Q3.prototype.IL=function(){this.C();Q3.Vf.IL.call(this)};
Q3.prototype.vr=function(){this.C();Q3.Vf.vr.call(this)};
Q3.prototype.FJ=function(){this.C();Q3.Vf.FJ.call(this)};
g.ob(Dmb,Q3);Dmb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(Gmb,g.I);g.k=Gmb.prototype;g.k.Ta=function(a,b,c,d){c=(0,g.ib)(c,d||this.B);a=g.uC(a,b,c);this.j.push(a);return a};
g.k.fJ=function(a,b,c,d){c=(0,g.ib)(c,d||this.B);a=xmb(a,b,c);this.j.push(a);return a};
g.k.Tc=function(a){g.vC(a);g.Ib(this.j,a)};
g.k.Uf=function(){g.vC(this.j);this.j.length=0};
g.k.xa=function(){this.Uf();g.I.prototype.xa.call(this)};g.w(Jmb,g.NV);g.k=Jmb.prototype;g.k.load=function(){g.NV.prototype.load.call(this);if(!T3(this)){var a=g.RTa(this.player.getVideoData());a?(a=Imb(a,Kmb(this)),U3(this,a,!1)):Lmb(this)}};
g.k.unload=function(){U3(this,null);this.C&&(this.C.abort(),this.C=null);g.NV.prototype.unload.call(this)};
g.k.Nh=function(a,b){return T3(this)?"loadCustomEndscreenRenderer"===a?(a=Imb(b,"new"),U3(this,a),!0):null:null};
g.k.getOptions=function(){return T3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Yb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<dob.length;f++){var h=Math.abs(b.width-dob[f]);if(-1===e||d>=h)e=f,d=h}d=eob[e];this.B&&g.ls(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.ws(e.element,m,f);g.rs(e.element,n,p);g.bv(e.element,fob);256<m||256<f?g.Zu(e.element,"ytp-ce-large-round"):96<m||96<f?g.Zu(e.element,"ytp-ce-medium-round"):g.Zu(e.element,"ytp-ce-small-round");g.bv(e.element,gob);m=h.left+h.width/2;h=h.top+l/2;g.Zu(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.bv(e.element,eob);g.Zu(e.element,d);(e=g.yf(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.ls(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())Y3(this,this.endscreen.impressionUrls),(a=g.lF())&&this.endscreen.visualElement&&g.CF(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.Zu(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Zu(b,"ytp-ce-shown");Y3(this,c.impressionUrls);(b=g.lF())&&g.CF(b,c.visualElement);this.player.U().K&&this.player.ob("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.av(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.av(b,"ytp-ce-shown");this.player.U().K&&this.player.ob("endscreenelementhidden",a)}};
g.k.oba=function(a){var b=this;a.target===window&&(new g.Ru(function(){for(var c=g.u(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.bv(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var dob=[346,426,470,506,570,640,853,1280,1920],eob="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),gob=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],fob=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Ymb={Nua:"current",DVa:"new"};var $mb={CLOSE:"close",uZa:"openUrl",SUBSCRIBE:"subscribe"},anb={Vsa:"click",CLOSE:"close",KGa:"hidden",w4a:"rollOut",x4a:"rollOver",m6a:"shown"};cnb.prototype.Ve=function(){var a=dnb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var aob={tna:"anchored",R1:"branding",CHANNEL:"channel",Dua:"cta",NGa:"highlightText",OKa:"label",PLAYLIST:"playlist",d1a:"popup",l9a:"speech",SUBSCRIBE:"subscribe",bcb:"title",VIDEO:"video",Bjb:"website"},$nb={R1:"branding",Cqa:"card",Owa:"drawer",MGa:"highlight",aRa:"marker",J2a:"promotion",TEXT:"text",hlb:"widget"};g.w(e4,g.I);g.k=e4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.PJ(a,b,{id:c,namespace:"annotations_module"});d&&this.Xa.set(a,d);e&&this.eb.set(a,e);this.context.J.Bf([a])};
g.k.YF=function(){this.context.B.subscribe("resize",this.kH,this)};
g.k.Kb=function(){return this.element};
g.k.JL=function(a,b,c,d,e,f){if(this.tb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Rf(this.Kb())};
g.k.kH=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=$3(a);if(f){var h=knb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Pf||!1,n=g.vB(f||"");m&&n&&(n.v||n.list)?e.context.J.No(n.v,b,n.list,!1):g.ZG(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);q4(this.context.logger,c,l,d);jnb(f)||(c=g.lF(),d=b.itct,c&&d&&g.FF(c,g.jF(d)))}};
g.k.xa=function(){this.Xa.clear();this.eb.clear();g.I.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.N(this,a);return a.element};g.w(mnb,e4);g.k=mnb.prototype;g.k.nt=function(){this.va&&j4(this,this.va)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.xs(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.kH=function(){var a=this.isAvailable();g.ys(this.Kb(),a);g.cv(this.context.J.getRootNode(),g.hZ.IV_DRAWER_ENABLED,a);K3(this.J)};
g.k.destroy=function(){this.J.qB(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.tE(this.ma);g.AC(this.Ra);this.Wa&&this.Wa.dispose();this.G&&this.G.dispose();e4.prototype.destroy.call(this)};
g.k.findLastIndex=function(a){if(0===this.cards.length)return 0;var b=g.Eb(this.cards,function(c){return a.If.startMs>c.If.startMs||a.If.startMs===c.If.startMs&&a.If.timestamp>=c.If.timestamp?!0:!1});
return-1===b?0:b+1};
g.k.Z5=function(){if(this.C){q4(this.context.logger,n4(this).nj.close);var a=g.lF();a&&this.N&&g.FF(a,this.N);i4(this)}};
g.k.x6=function(){g.cv(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.X8=function(){var a=g.lF(),b=n4(this);b=b?b.Mf:this.Mf;a&&b&&g.DF(a,[b])};
g.k.W8=function(){var a=g.lF(),b=n4(this);b=b?b.Mf:this.Mf;a&&b&&g.EF(a,[b])};
g.k.D2=function(){var a=n4(this);q4(this.context.logger,a.nj.B0);var b=g.lF();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.Qj&&c.push(a.Qj);a.Mf&&c.push(a.Mf);0<c.length&&g.DF(b,c)}else g.DF(b,[a.Qj,a.Mf])};
g.k.Y8=function(){var a=g.lF(),b=n4(this);a&&b&&g.EF(a,[b.Qj])};
g.k.C2=function(a){var b=n4(this),c=g.lF();this.j?a?(a=this.context.logger,q4(a,b.nj.YK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Qj&&g.FF(c,b.Qj)):(a=this.context.logger,q4(a,b.nj.YK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Mf&&g.FF(c,b.Mf)):(a=this.context.logger,q4(a,b.nj.YK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Mf&&g.FF(c,this.Mf))};g.w(o4,e4);o4.prototype.YF=function(){e4.prototype.YF.call(this);Bnb(this)};
o4.prototype.show=function(){e4.prototype.show.call(this);var a=g.lF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.DF(a,[g.jF(b.itct)])};
o4.prototype.hide=function(){e4.prototype.hide.call(this);var a=g.lF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.EF(a,[g.jF(b.itct)])};g.w(p4,o4);p4.prototype.mx=function(){g.Zu(this.Kb(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",La:["branding-img","iv-click-target"],X:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.ys(this.B,!1);var b=this.createElement({I:"button",La:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Kb().appendChild(b);var c=this.annotation.Ve();c&&f4(this,b,c,this.annotation.id,a.session_data);Fnb(this,a)};
p4.prototype.show=function(){if(!this.isActive&&(o4.prototype.show.call(this),this.N||(this.mx(),this.N=!0),g.ys(this.Kb(),!0),this.isActive=!0,this.B)){try{Cnb(this,this.B)}catch(a){}g.Zu(this.context.J.getRootNode(),"ytp-branding-shown")}};
p4.prototype.hide=function(){this.isActive&&(o4.prototype.hide.call(this),g.ys(this.Kb(),!1),this.isActive=!1,g.av(this.context.J.getRootNode(),"ytp-branding-shown"))};
p4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);o4.prototype.destroy.call(this)};g.w(Hnb,o4);g.k=Hnb.prototype;
g.k.mx=function(){var a=this,b=this.annotation.data;if("cta"===this.annotation.style)var c=6;else if("video"===this.annotation.style||"playlist"===this.annotation.style)c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Kb().setAttribute("aria-hidden","true");this.Kb().setAttribute("aria-label","Promotion");this.Kb().tabIndex=0;var e=this.annotation.Ve(),f=b.image_url;if(f){var h=this.createElement({I:"div",La:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",ya:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",ya:b.playlist_length.toString()}),h.appendChild(f));e&&f4(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Se(f,$3(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",ya:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",ya:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",La:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",La:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",ya:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&f4(this,
this.Kb(),e,this.annotation.id,b.session_data,void 0,c)}g.Zu(this.j,"iv-click-target");e&&f4(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",ya:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",ya:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",La:["yt-badge","iv-promo-badge-live"],ya:"LIVE NOW"})),g.Zu(this.j,"iv-click-target"),e&&f4(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",La:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.Ta(this.B,"click",function(q){Knb(a,5E3,q)});
c.appendChild(this.B);g.ys(this.B,!1);this.context.j.Ta(this.Kb(),"mouseover",this.R7,this);this.context.j.Ta(this.Kb(),"mouseout",this.Q7,this);this.context.j.Ta(this.Kb(),"touchend",function(q){Knb(a,5E3,q)});
this.C=this.createElement({I:"button",La:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.Ta(this.C,"click","cta"===this.annotation.style&&b.text_line_3?this.M7:this.L7,this);c.appendChild(this.C);g.$u(this.Kb(),d);h&&(g.Of(this.Kb(),h),n&&h.appendChild(n));g.Of(this.Kb(),this.N);g.Of(this.Kb(),c)};
g.k.show=function(){this.isActive||(o4.prototype.show.call(this),this.Y||(this.mx(),this.Y=!0),g.ys(this.Kb(),!0),g.yg(function(){g.av(this.Kb(),"iv-promo-inactive")},100,this),this.Kb().removeAttribute("aria-hidden"),this.isActive=!0,Mnb(this),Inb(this),Jnb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.Zu(this.Kb(),"iv-promo-inactive"),this.isActive=!1,this.Kb().setAttribute("aria-hidden","true"))};
g.k.JL=function(a,b,c,d,e,f){return this.isCollapsed?!1:o4.prototype.JL.call(this,a,b,c,d,e,f)};
g.k.R7=function(a){this.Z=!0;Knb(this,500,a)};
g.k.Q7=function(){this.Z=!1;Lnb(this)};
g.k.L7=function(a){a.stopPropagation();this.hide()};
g.k.M7=function(a){a.stopPropagation();Mnb(this);this.isCollapsed=!0;g.Zu(this.Kb(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();o4.prototype.destroy.call(this)};g.w(Onb,g.NV);g.k=Onb.prototype;g.k.Nh=function(a,b){if(!cob(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.l2(b))&&Tnb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(qnb(this.j,b),K3(this.player)),!0}return null};
g.k.getOptions=function(){return cob(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.du=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.MT(b)||g.WT(this.player.app)?!1:1===c&&!b.kV||a.Na.get(b.videoId)||g.AT(b)||g.STa(b)?!0:!1};
g.k.OJ=function(){if(this.C){var a=this.player.qb().getVideoContentRect(!0);g.ws(this.C.element,a.width,a.height);g.rs(this.C.element,a.left,a.top)}if(this.j){var b=this.player.En();a=this.j;b=b.width;g.cv(a.D,"iv-drawer-small",426>=b);g.cv(a.D,"iv-drawer-big",1280<=b)}};
g.k.E2=function(a){Qnb(this,a.state);g.EG(a.state,2)&&(this.Nk()&&this.hp()&&2!==this.player.getPresentingPlayerType()&&this.rB(!1),this.qB(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.FB(h)&&h.responseXML?h.responseXML:null)&&(Tnb(b,h),g.Zu(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.NV.prototype.load.call(this);Qnb(this,this.player.Xb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.TC()&&(a=Unb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Na.get(d);f&&Vnb(e,f);f=f&&(f.dN||f.pH);if(!c.Jx||f)c.Wa?Rnb(this,c.Wa,e):(this.K=function(){if(!b.Z)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.zT(h))&&!b.ma&&Znb(b,h)},this.player.addEventListener("videodatachange",this.K));
g.kU(this.player,this.C.element,4);this.OJ();(f=g.AT(c))&&Ynb(this,f);(f=g.STa(c))&&f.featuredChannel&&bob(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.dh=g.Af("ytp-cards-button",this.player.getRootNode());g.zT(c)&&Znb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Wa&&Rnb(this,b.Wa,a)};
g.k.unload=function(){this.player.Ff("annotations_module");for(var a=g.u(Object.keys(this.N)),b=a.next();!b.done;b=a.next())this.N[b.value].destroy();this.Y=null;this.j&&(this.j.destroy(),this.j=null,K3(this.player));this.Z=!1;this.G&&(this.G.abort(),this.G=null);this.ma=!1;this.N={};this.B.hide();g.NV.prototype.unload.call(this);this.C.detach();this.K&&(this.player.removeEventListener("videodatachange",this.K),this.K=null)};
g.k.SZ=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Wnb(this):this.load())};
g.k.Nk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.ma};
g.k.hp=function(){return!!this.j&&this.j.C};
g.k.rB=function(a,b,c){b=void 0===b?!1:b;this.Nk();this.j&&(a?c?h4(this.j,c,b):h4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):i4(this.j))};
g.k.qB=function(a,b){this.player.ra(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.U().Na.unsubscribe("vast_info_card_add",this.SZ,this);g.av(this.player.getRootNode(),g.hZ.IV_DRAWER_OPEN);for(var a=this.va,b=g.Ju,c=0,d=a.length;c<d;c++)b.Uj(a[c]);this.va.length=0;g.NV.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.N(this,a);return a.element};g.MV("annotations_module",Onb);g.MV("creatorendscreen",Jmb);})(_yt_player);
